// ═══════════════════════════════════════════════
// AD CREATOR — Icon Map
// Lucide outline icons per node type + UI
// ═══════════════════════════════════════════════
import {
  Globe,
  Target,
  Heading1,
  MousePointerClick,
  Layers,
  PenLine,
  FilePen,
  Download,
  Brush,
  Wand2,
  Image,
  LayoutTemplate,
  FolderDown,
  FlaskConical,
  KeyRound,
  AlertTriangle,
  Plus,
  X,
  ChevronRight,
  Palette,
  Megaphone,
  Radio,
  Pencil,
  Grid2x2,
  // Campaign type icons
  Eye,
  TrendingUp,
  Mail,
  Rocket,
  Sparkles,
  RefreshCw,
  // Banner group icons
  Users,
  ArrowUpRight,
  CalendarDays,
  Heart,
  // Wizard flow icons
  FileText,
  ListChecks,
  Bold,
  Italic,
  Underline,
  AlignLeft,
  AlignCenter,
  AlignRight,
  Moon,
  Sun,
  type LucideIcon,
} from 'lucide-react'

export const NODE_ICONS: Record<string, LucideIcon> = {
  campaignNode:          Megaphone,
  channelNode:           Radio,
  webImportNode:         Globe,
  promptNode:            Target,
  headlineNode:          Heading1,
  ctaNode:               MousePointerClick,
  headlineCTANode:       PenLine,
  copyVariantsNode:      FilePen,
  xToolsImportNode:      Download,
  copyGroupNode:         Layers,
  styleNode:             Brush,
  imageGenNode:          Wand2,
  bgLibraryNode:         Image,
  bannerComposerNode:    LayoutTemplate,
  batchExportNode:       FolderDown,
  themeNode:             Palette,
  creativeNode:          Pencil,
  bannerGridNode:        Grid2x2,
  briefNode:             FileText,
  headlineProposalsNode: ListChecks,
}

export type { LucideIcon }

export {
  FlaskConical,
  KeyRound,
  AlertTriangle,
  Plus,
  X,
  ChevronRight,
  // Campaign icons
  Eye,
  TrendingUp,
  Mail,
  Rocket,
  Sparkles,
  RefreshCw,
  Users,
  ArrowUpRight,
  CalendarDays,
  Heart,
  // Wizard flow icons
  FileText,
  ListChecks,
  Bold,
  Italic,
  Underline,
  AlignLeft,
  AlignCenter,
  AlignRight,
  Moon,
  Sun,
}
